spring.application.name=city_card

# PostgreSQL ba?lant? bilgileri
spring.datasource.url=jdbc:postgresql://localhost:5432/city_card
spring.datasource.username=postgres
spring.datasource.password=12345
spring.datasource.driver-class-name=org.postgresql.Driver

# JPA ve Hibernate ayarlar?
spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

# SQL gösterimi
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true


springdoc.swagger-ui.path=/swagger-ui.html

spring.jackson.date-format=yyyy-MM-dd
spring.jackson.time-zone=Europe/Istanbul

cloudinary.cloud_name=da5vtbdbm
cloudinary.api_key=955765985525971
cloudinary.api_secret=YybR4y2DCBC2MVB_Hhr5C88L6K8

spring.servlet.multipart.enabled=true
spring.servlet.multipart.max-file-size=10MB
spring.servlet.multipart.max-request-size=10MB


